apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: go-http-server-secrets
  labels:
    app: go-http-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: go-http-server-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: /dev/go-http-server/database
      property: url
