apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The “Production” namespace field is not included here because each service
# has its own (dedicated) namespace

resources:
  # Per-service overlays (Each service has its own namespace, quota, and network policy.)
  # Add new service here
  - go-http-server
