apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../bases/testapp

images:
  - name: docker.io/idiots718/testapp
    newTag: dev-latest

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/resource-patch.yaml
  - path: patches/ingress-patch.yaml
  - path: patches/hpa-patch.yaml
